// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/which/which.d.ts
declare module "which" {
  function when (cmd: string, cb: (err: Error, path: string) => void): void;
  namespace when {
    function sync(cmd: string): string;
  }

  export = when;
}
