// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/90dc1f65a2ffa5125ced3d64ef5ba06262ac7ee7/archiver/archiver.d.ts
declare module "archiver" {
    import * as FS from 'fs';
    import { Transform } from 'stream';

    interface EntryData {
        name?: string;
    }

    interface Options {

    }

    function archiver(format: string, options?: Options): archiver.Archiver;

    namespace archiver {
        function create(format: string, options?: Options): Archiver;

        interface Archiver extends Transform {
            pipe(writeStream: FS.WriteStream): void;
            file(filepath: string, name: EntryData): void;
            append(source: FS.ReadStream | Buffer | string, name: EntryData): void;
            finalize(): void;
        }
    }

    export = archiver;
}
